{ ... }:{
  # generated by wgbond
  # networking.wg-quick.interfaces."keter"={privateKeyFile="/secrets/wg-keter.ed25519.base64";address=["10.0.10.8" "fd80:c4b4::8"];peers=[{publicKey="AhOeGzMO2evGSkyI+IJVNoF9+POHGlnk+/XRWK4Jvhw=";allowedIPs=["10.0.10.0/24" "fd80:c4b4::/48" "10.0.10.1/32" "fd80:c4b4::1/128"];persistentKeepalive=30;endpoint="51.15.83.8:61111";}];};

}
